import { useEffect } from 'react'
import { Layout, Panel } from './components/Layout'
import { OutputPanel } from './components/OutputPanel'
import { SettingsPanel } from './components/SettingsPanel'
import { usePasswordGenerator } from './hooks/usePasswordGenerator'
import { usePasswordHistory } from './hooks/usePasswordHistory'
import { usePasswordOptions } from './hooks/usePasswordOptions'

let hasAutoGeneratedInitialPassword = false

function App() {
  const { options, updateOption, poolSize, strength } = usePasswordOptions()
  const { addPassword, addPasswords } = usePasswordHistory()
  const generator = usePasswordGenerator({
    options,
    addPasswordToHistory: addPassword,
    addPasswordsToHistory: addPasswords,
  })

  useEffect(() => {
    if (hasAutoGeneratedInitialPassword || !generator.canGenerate) {
      return
    }

    hasAutoGeneratedInitialPassword = true
    generator.generate()
  }, [generator])

  return (
    <Layout
      settings={
        <Panel
          title="Settings"
          description="Tune length, character sets, and ambiguity filters."
        >
          <SettingsPanel
            options={options}
            poolSize={poolSize}
            onOptionChange={updateOption}
          />
        </Panel>
      }
      output={
        <Panel
          title="Output"
          description="Generate, copy, and evaluate the current password."
        >
          <OutputPanel
            password={generator.password}
            strength={strength}
            poolSize={poolSize}
            canGenerate={generator.canGenerate}
            hasGeneratedPassword={generator.hasGeneratedPassword}
            error={generator.error}
            onGenerate={generator.generate}
            onRegenerate={generator.regenerate}
            onGenerateMultiple={() => generator.generateMultiple(10)}
          />
        </Panel>
      }
      history={
        <Panel
          title="History"
          description="The last 10 generated passwords will be stored locally."
        >
          <div className="rounded-2xl border border-dashed border-nordic-border bg-nordic-bg p-5 text-sm text-nordic-muted">
            History and persistence arrive in Phase 6.
          </div>
        </Panel>
      }
    />
  )
}

export default App
