import { useEffect } from 'react'
import { BulkResults } from './components/BulkResults'
import { Layout, Panel } from './components/Layout'
import { OutputPanel } from './components/OutputPanel'
import { PasswordHistory } from './components/PasswordHistory'
import { SettingsPanel } from './components/SettingsPanel'
import { usePasswordGenerator } from './hooks/usePasswordGenerator'
import { usePasswordHistory } from './hooks/usePasswordHistory'
import { usePasswordOptions } from './hooks/usePasswordOptions'

let hasAutoGeneratedInitialPassword = false

function App() {
  const { options, updateOption, poolSize, strength } = usePasswordOptions()
  const { history, addPassword, addPasswords } = usePasswordHistory()
  const generator = usePasswordGenerator({
    options,
    addPasswordToHistory: addPassword,
    addPasswordsToHistory: addPasswords,
  })

  useEffect(() => {
    if (hasAutoGeneratedInitialPassword || !generator.canGenerate) {
      return
    }

    hasAutoGeneratedInitialPassword = true
    generator.generate()
  }, [generator])

  return (
    <Layout
      settings={
        <Panel
          title="Settings"
          description="Tune length, character sets, and ambiguity filters."
        >
          <SettingsPanel
            options={options}
            poolSize={poolSize}
            onOptionChange={updateOption}
          />
        </Panel>
      }
      output={
        <Panel
          title="Output"
          description="Generate, copy, and evaluate the current password."
        >
          <OutputPanel
            password={generator.password}
            strength={strength}
            poolSize={poolSize}
            canGenerate={generator.canGenerate}
            hasGeneratedPassword={generator.hasGeneratedPassword}
            error={generator.error}
            onGenerate={generator.generate}
            onRegenerate={generator.regenerate}
            onGenerateMultiple={() => generator.generateMultiple(10)}
          />
        </Panel>
      }
      bulk={
        generator.bulkPasswords.length > 0 ? (
          <Panel
            title="Bulk Results"
            description="Ten generated passwords from the latest bulk run."
          >
            <BulkResults passwords={generator.bulkPasswords} />
          </Panel>
        ) : null
      }
      history={
        <Panel
          title="History"
          description="Newest generated passwords, masked until hover or focus."
        >
          <PasswordHistory history={history} />
        </Panel>
      }
    />
  )
}

export default App
